2024-04-27 18:58:06,596 
INFO 
NGROK URL : https://2f28-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 18:59:21,244 
INFO 
NGROK URL : https://da2e-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 18:59:21,427 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 18:59:21,434 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 18:59:47,023 
INFO 
NGROK URL : https://8d85-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 18:59:47,096 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 18:59:47,104 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 18:59:47,462 
INFO 
Call started...sid: CA168280ab5547ad3a35d2d2067f4a1cd6 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 65, in call_all_clinics

2024-04-27 18:59:57,781 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 19:01:12,513 
INFO 
NGROK URL : https://967e-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:01:12,587 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:01:12,594 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:01:12,965 
INFO 
Call started...sid: CAcab6e1f461807f024980055523b5dd84 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:02:09,734 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:02:18,890 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:02:48,480 
INFO 
NGROK URL : https://42d3-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:02:48,552 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:02:48,559 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:02:48,969 
INFO 
Call started...sid: CAfec892864e1253bd08c97cde6403c7b6 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:03:36,405 
INFO 
Unrecognizable speech at intro response, speech result:  
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 57, in handle_intro_response

2024-04-27 19:03:40,811 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:03:59,741 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:04:03,245 
INFO 
NGROK URL : https://be3e-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:04:03,317 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:04:03,324 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:04:03,860 
INFO 
Call started...sid: CA13a66b85e6353ab9a7c0d738ea8d4643 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:05:18,615 
INFO 
female doctors: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 101, in handle_number_female_doctors_response

2024-04-27 19:05:18,619 
INFO 
call was a success, male docs: 1, female docs: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 89, in handle_successful_call

2024-04-27 19:05:18,937 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 1, 'available_female_docs': 1, 'last_call_date': '2024-04-27', 'id': 54, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 93, in handle_successful_call

2024-04-27 19:05:26,639 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:05:30,672 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:05:31,033 
INFO 
Call started...sid: CA83bd177dee18efdb534550e21e4fe152 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:06:47,404 
INFO 
female doctors: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 101, in handle_number_female_doctors_response

2024-04-27 19:06:47,408 
INFO 
call was a success, male docs: 1, female docs: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 89, in handle_successful_call

2024-04-27 19:06:47,715 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic 2", 'address': '2323 dele st', 'phone_number': '(314) 940-2059', 'rating': 4.2, 'available_male_docs': 1, 'available_female_docs': 4, 'last_call_date': '2024-04-27', 'id': 55, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 93, in handle_successful_call

2024-04-27 19:06:58,083 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:07:41,815 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:15:05,955 
INFO 
NGROK URL : https://6f64-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:15:06,028 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:15:06,035 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:15:07,314 
INFO 
Call started...sid: CAd324e57ff122a955a8ad260cc5c6ecd5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:15:28,196 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:15:33,885 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:15:41,838 
INFO 
NGROK URL : https://3d27-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:15:41,904 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:15:41,911 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:15:42,234 
INFO 
Call started...sid: CAba16c4f9c228b5e694a7dd0667116ea4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:16:30,779 
INFO 
Unrecognizable speech at intro response, speech result:  
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 57, in handle_intro_response

2024-04-27 19:16:30,783 
INFO 
response not understood 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 38, in handle_unrecognizable_speech_response

2024-04-27 19:16:44,513 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:16:54,117 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:16:56,999 
INFO 
NGROK URL : https://4d34-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:16:57,063 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:16:57,070 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:16:57,418 
INFO 
Call started...sid: CAe04764c3b301ffecff0d58883bc3a434 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:18:02,507 
INFO 
unsuccessful response for num male docs:  
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 76, in handle_number_male_doctors_response

2024-04-27 19:18:02,511 
INFO 
response not understood 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 38, in handle_unrecognizable_speech_response

2024-04-27 19:18:28,330 
INFO 
response not understood 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 38, in handle_unrecognizable_speech_response

2024-04-27 19:18:39,476 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:18:43,356 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:19:14,277 
INFO 
NGROK URL : https://1e6e-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 12, in <module>

2024-04-27 19:19:14,355 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:19:14,362 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:19:15,453 
INFO 
Call started...sid: CA17de6dae110dc7f5ea21a6a3547b1144 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:19:26,570 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:40:06,747 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 19:51:54,397 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 19:51:54,398 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 19:51:54,877 
INFO 
Call started...sid: CA8ead9d0256b7b3e33d3942d2f431af5c 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 19:52:09,657 
INFO 
FORM: {'Called': '+13149402059', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA8ead9d0256b7b3e33d3942d2f431af5c', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 22, in detect_nav_menu

2024-04-27 19:52:09,660 
INFO 
NGROK URL : https://480c-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 28, in detect_nav_menu

2024-04-27 19:52:15,691 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 19:52:18,473 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:04:36,174 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:04:36,175 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:04:36,887 
INFO 
Call started...sid: CA8ad65e1f2ae7ad0062c8fd21926dd382 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 20:04:52,951 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 20:05:58,861 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:06:01,338 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:06:01,339 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:06:02,030 
INFO 
Call started...sid: CAbd71ffd0d3fac2335007e8eb9ca9f065 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 20:06:17,897 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 20:07:03,385 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:07:06,143 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:07:06,145 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:07:06,466 
INFO 
Call started...sid: CA4a3310d517f69164464841ca9dc749f3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 20:07:32,333 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 20:07:40,904 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:10:34,076 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:10:34,077 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:10:34,598 
INFO 
Call started...sid: CA4d38f6ba8d4754db9e29e4a774c33594 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 20:10:50,197 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 20:12:53,257 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:15:18,591 
INFO 
received phone number: (314) 940-2059 
 received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:15:18,592 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:15:18,593 
INFO 
URL: https://d766-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 31, in make_call

2024-04-27 20:15:19,412 
INFO 
Call started...sid: CA0d9848c519b27e23e86c18fba779c3e9 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 75, in call_all_clinics

2024-04-27 20:16:04,384 
INFO 
call was a success, male docs: 68, female docs: 98 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 71, in handle_successful_call

2024-04-27 20:16:05,381 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 68, 'available_female_docs': 98, 'last_call_date': '2024-04-27', 'id': 54, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 75, in handle_successful_call

2024-04-27 20:16:16,093 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 39, in check_call_status

2024-04-27 20:16:21,034 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 103, in call_all_clinics

2024-04-27 20:27:34,147 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:27:34,148 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:27:34,764 
INFO 
Call started...sid: CAfdd9b9ae95b046e62b25eba3644b8c8c 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:28:16,440 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 20:29:21,035 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 20:29:24,156 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:29:24,157 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:29:24,576 
INFO 
Call started...sid: CAdb5777bb46867286910cd47f62b83ac7 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:30:20,897 
INFO 
call was a success, male docs: 56, female docs: 12 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 71, in handle_successful_call

2024-04-27 20:30:21,229 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-27', 'id': 54, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 75, in handle_successful_call

2024-04-27 20:30:31,306 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 20:31:25,081 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:31:25,484 
INFO 
Call started...sid: CAc3a155a7c3748cc7340bf78d009a87d9 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:32:06,625 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 20:32:08,939 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 56 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:32:09,285 
INFO 
Call started...sid: CAa9828ec1a2c4ed52ad51f6b9dedd417b 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:33:10,108 
INFO 
call was a success, male docs: 11, female docs: 25 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 71, in handle_successful_call

2024-04-27 20:33:10,345 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic 3", 'address': '1212 apple st', 'phone_number': '(314) 940-2059', 'rating': 2.3, 'available_male_docs': 11, 'available_female_docs': 25, 'last_call_date': '2024-04-27', 'id': 56, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 75, in handle_successful_call

2024-04-27 20:50:12,720 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 20:50:18,649 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:50:18,650 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:50:20,266 
INFO 
Call started...sid: CA9fdd05cacebe270af5f531c8c83b4ea4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:50:30,532 
INFO 
intro mess it is now: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:50:50,783 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:50:50,892 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:51:12,154 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 20:53:55,275 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 20:53:58,820 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:53:58,821 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:53:59,209 
INFO 
Call started...sid: CA603f9d96e4526421ab6d0c75fde5c6f1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:54:06,234 
INFO 
intro mess it is now: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:54:10,979 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:54:11,082 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:54:29,851 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:54:40,504 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 20:56:32,100 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 20:56:35,741 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 20:56:35,741 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 20:56:36,654 
INFO 
Call started...sid: CAcc7eda261142effeac3800876256b7b5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 20:56:51,835 
INFO 
intro mess it is now: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:57:10,797 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:57:10,901 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:57:28,821 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 26, in intro_message

2024-04-27 20:57:34,038 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:03:04,871 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:06:17,589 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:06:17,590 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:06:18,062 
INFO 
Call started...sid: CA8a849f1d7c0e2c7734aafcca56663ff5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:06:27,460 
INFO 
intro mess it is now: 1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 28, in intro_message

2024-04-27 21:06:39,483 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 28, in intro_message

2024-04-27 21:06:39,607 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 28, in intro_message

2024-04-27 21:06:48,700 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 28, in intro_message

2024-04-27 21:06:49,292 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:13:18,259 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:13:21,598 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:13:21,599 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:13:22,032 
INFO 
Call started...sid: CAa4e6d47fac828eb1430ade8bd09ab8e1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:13:36,047 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:13:48,270 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:13:48,383 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:07,952 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:08,053 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:27,865 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:27,972 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:50,496 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:14:57,251 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 21:15:03,543 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:15:03,544 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:15:03,888 
INFO 
Call started...sid: CA4b831040f1ff91934043878ac2a908d0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:15:13,504 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:15:34,521 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:15:34,640 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:15:40,788 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:00,630 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:00,733 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:06,978 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:27,666 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:27,767 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:33,909 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:54,703 
INFO 
intro mess it is now: 3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:16:54,804 
INFO 
intro mess it is now: 4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:17:01,041 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:17:09,513 
INFO 
intro mess it is now: 2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 31, in intro_message

2024-04-27 21:17:12,006 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:17:45,451 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:18:55,106 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:18:55,107 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:18:55,518 
INFO 
Call started...sid: CAb8166bfda364a0f3b1b06ed4a091a088 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:19:05,579 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:19:11,507 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:19:16,590 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:19:20,286 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:19:22,575 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:19:22,575 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:19:23,078 
INFO 
Call started...sid: CA0a850ce557430afa3c6f4c6a3b2c9054 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:19:38,445 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:19:42,741 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:19:42,911 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:20:03,324 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:20:03,767 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:20:04,414 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:20:17,984 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:25:37,683 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:25:37,683 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:25:38,499 
INFO 
Call started...sid: CA8ceb8e9d2b98c1f51823b8e897c17ce8 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:25:51,598 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:26:10,114 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:26:10,213 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:26:16,464 
INFO 

UPDATED ITERATION COUNT:  4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:26:19,636 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:33:10,815 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:33:15,795 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:33:15,797 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:33:16,389 
INFO 
Call started...sid: CA747fc0d3748b2508618c67df386578e5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:33:32,405 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:33:52,382 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:33:52,489 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:33:53,997 
INFO 

UPDATED ITERATION COUNT:  4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 32, in intro_message

2024-04-27 21:33:57,772 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:34:00,091 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:36:13,072 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:36:13,072 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:36:13,919 
INFO 
Call started...sid: CA44eb58b771f60089db5c67667f19055d 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:36:23,000 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:33,486 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:33,589 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:37,555 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:37,661 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:40,457 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:40,574 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:42,439 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:42,542 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:44,673 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:36:44,821 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:39:19,670 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:39:24,558 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:39:24,558 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:39:25,032 
INFO 
Call started...sid: CAf0d8cb0e881a2d0b21552b6c8b7aa816 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:39:46,127 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:40:04,126 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:40:06,219 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:40:06,220 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:40:06,707 
INFO 
Call started...sid: CAa54e9f26c37e4556d5343a2708a388f0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:40:21,491 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 35, in intro_message

2024-04-27 21:40:29,326 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 35, in intro_message

2024-04-27 21:40:33,080 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:41:27,484 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:41:29,606 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:41:29,607 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:41:29,994 
INFO 
Call started...sid: CAd56972df60a97b18e88a7886aefab73e 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:41:42,798 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:41:53,667 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:41:53,773 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:13,425 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:13,533 
INFO 

UPDATED ITERATION COUNT:  4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:19,671 
INFO 

UPDATED ITERATION COUNT:  5
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:25,924 
INFO 

UPDATED ITERATION COUNT:  6
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:32,066 
INFO 

UPDATED ITERATION COUNT:  7
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:34,727 
INFO 

UPDATED ITERATION COUNT:  8
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:42:36,764 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:42:38,044 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:45:46,215 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:45:46,215 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:45:46,595 
INFO 
Call started...sid: CA2e16ec473b64a0e9e2a098af4ee045a1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:45:54,817 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:45:58,713 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:45:58,830 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:46:01,577 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:46:02,161 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:47:46,900 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:47:51,659 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:47:51,660 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:47:52,142 
INFO 
Call started...sid: CAbb6e1d2b35d4930409128ddfb366f4ed 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:48:00,549 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:48:08,459 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:48:08,565 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:48:27,910 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:48:28,381 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:56:08,189 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:56:16,471 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:56:16,471 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:56:16,970 
INFO 
Call started...sid: CA0f1e46c1180a57af82553c41371a109f 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:56:27,833 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:56:36,113 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:56:36,220 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:56:56,567 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 21:56:58,191 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 21:58:43,948 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 21:58:46,234 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 21:58:46,235 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 21:58:47,035 
INFO 
Call started...sid: CA201399166d4b02ba4b38bc74c9c06763 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 21:58:56,567 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:59:06,624 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:59:06,720 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:59:24,079 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 21:59:28,392 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:02:07,950 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:02:11,552 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:02:11,554 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:02:11,935 
INFO 
Call started...sid: CA3326f1a66b7e9373536d7f6bd2c3d9aa 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:02:21,303 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:25,961 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:29,988 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 22:02:31,633 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:02:31,633 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:02:31,961 
INFO 
Call started...sid: CAb0a7c7b90ca7d9c01ccb0d196e371cff 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:02:41,298 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:43,832 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:43,949 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:50,612 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 34, in intro_message

2024-04-27 22:02:52,770 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:05:08,914 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:05:15,539 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:05:15,540 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:05:15,930 
INFO 
Call started...sid: CA0a64d4100c1cfa2714384640f035b2d2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:05:30,099 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:05:34,174 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:05:34,290 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:05:40,856 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:05:40,951 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:06:00,082 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:06:00,205 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:06:17,599 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:06:22,803 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:06:45,876 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:06:46,206 
INFO 
Call started...sid: CAafa325ddb2d5cbd7d503d4c3fccf1582 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:06:59,705 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:05,825 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:05,930 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:07,871 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:07,989 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:10,316 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:10,416 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:12,790 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:13,878 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 22:07:17,538 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:07:17,539 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:07:17,934 
INFO 
Call started...sid: CA549187a4f4d9be7458995471de814504 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:07:25,473 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:28,720 
INFO 

UPDATED ITERATION COUNT:  0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:28,897 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:30,576 
INFO 

UPDATED ITERATION COUNT:  1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:30,684 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:32,343 
INFO 

UPDATED ITERATION COUNT:  2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:32,454 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:48,943 
INFO 

UPDATED ITERATION COUNT:  3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 33, in intro_message

2024-04-27 22:07:49,071 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:24:03,938 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:24:13,214 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:24:13,218 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:24:14,120 
INFO 
Call started...sid: CA176c1e3c3ae381af45032c138f2b1459 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:24:16,218 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 22:25:14,937 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:25:14,937 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:25:15,275 
INFO 
Call started...sid: CAffd64a694f33bc7448bf4edcaded7ca4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:25:17,865 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-27 22:26:12,647 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:26:12,648 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:26:13,002 
INFO 
Call started...sid: CAddf980441f224cc5b0ede0906fe38447 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:26:33,667 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:26:39,895 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:26:43,113 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:26:43,113 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:26:43,639 
INFO 
Call started...sid: CAe85dd5018ec63f87ca6f13b642f4b1f8 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:27:11,704 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:27:31,974 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:27:40,141 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:28:06,282 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:28:08,564 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:28:08,564 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:28:09,063 
INFO 
Call started...sid: CAccd67b4f1c06fefba5b446c413aabe7b 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:28:28,376 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:28:40,274 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 22:28:48,442 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 22:28:50,916 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 22:28:50,917 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 22:28:51,248 
INFO 
Call started...sid: CA89111c93056b8e663f552650568ca5ac 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 22:29:10,507 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:29:19,188 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:29:25,065 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:29:30,244 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 22:29:37,559 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:04:43,525 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:05:02,411 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:05:02,411 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:05:03,289 
INFO 
Call started...sid: CA926da93bae2c1466ee9b58a92c89d78b 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:05:26,298 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:05:35,237 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:05:45,083 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:05:55,516 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:06:04,073 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:06:10,159 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:09:52,893 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:10:30,961 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:10:30,962 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:10:31,418 
INFO 
Call started...sid: CA75898f79862bd870f3936f06854adaaf 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:10:49,577 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:10:57,641 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:11:01,425 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:11:03,924 
INFO 
response not understood on path: /call/intro_message/54?iteration_count=4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 22, in handle_unrecognizable_response

2024-04-27 23:11:07,499 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-27', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 96, in handle_failed_call

2024-04-27 23:11:17,931 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:13:54,999 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:13:57,860 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:13:57,860 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:13:58,241 
INFO 
Call started...sid: CAc4c14eff4bd9964b0662d093e57a9508 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:14:13,872 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:14:44,333 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:44:38,085 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:44:38,085 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:44:38,599 
INFO 
Call started...sid: CAd01dbf08afd2721ffcd856a834d86ef6 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:44:59,293 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:45:10,377 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:45:14,273 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:45:14,273 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:45:14,778 
INFO 
Call started...sid: CA492f8b60c3e79400b1e12a51b90113de 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:45:30,590 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:45:40,891 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:45:43,671 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:45:43,671 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:45:44,001 
INFO 
Call started...sid: CA384ae7678dde738b097d19e3e5f0b601 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:46:22,579 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-27 23:46:25,437 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-27 23:47:14,313 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-27 23:47:16,007 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-27 23:47:16,008 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-27 23:47:16,433 
INFO 
Call started...sid: CAd5e7da8cdf86cfceb350d011981ef9eb 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-27 23:47:56,462 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-27 23:48:05,441 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-27 23:48:14,806 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-27 23:48:23,280 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-27 23:48:32,027 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-27', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 128, in handle_failed_call

2024-04-27 23:48:43,891 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:06:22,897 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:06:28,239 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:06:28,240 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:06:28,675 
INFO 
Call started...sid: CAf0a10687c696953c476a28886d8bdf23 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:07:07,261 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:07:14,389 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:07:19,765 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:07:26,765 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:07:33,426 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 135, in handle_failed_call

2024-04-28 00:07:46,203 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:08:50,248 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:08:55,784 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:08:55,785 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:08:56,324 
INFO 
Call started...sid: CAe0182e41229a7a6be3b04811eb56f252 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:09:27,328 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:09:35,995 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:09:43,775 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:09:49,305 
INFO 
response not understood on path: /call/intro_message/54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 26, in handle_unrecognizable_response

2024-04-28 00:09:52,920 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 135, in handle_failed_call

2024-04-28 00:09:58,471 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:19:13,699 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:19:17,058 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:19:17,059 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:19:17,488 
INFO 
Call started...sid: CAa28a37c0c8b7f6d619a042cc86bd974d 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:20:09,177 
INFO 
response not understood on path: /intro_message/54?iteration_count=2&timeout_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:20:25,130 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:20:27,397 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:21:16,548 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:21:16,549 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:21:17,005 
INFO 
Call started...sid: CAef5465bcea6ac86b35b44ecbf71de9bd 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:21:31,349 
INFO 
response not understood on path: call/intro_message/54?iteration_count=-1&timeout_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:21:39,756 
INFO 
response not understood on path: call/intro_message/54?iteration_count=-2&timeout_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:21:48,019 
INFO 
response not understood on path: call/intro_message/54?iteration_count=-3&timeout_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:21:56,646 
INFO 
response not understood on path: call/intro_message/54?iteration_count=-4&timeout_count=4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:22:05,150 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 00:22:08,613 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:23:59,092 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:24:00,923 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:24:00,924 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:24:01,374 
INFO 
Call started...sid: CAd40e9f9dcf5fbf2af9980996f14e827b 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:24:11,976 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:24:16,072 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:24:20,927 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:24:20,928 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:24:21,277 
INFO 
Call started...sid: CAe27755fd8821b53dadda487d6872fa03 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:24:33,836 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:24:42,722 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:24:51,275 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 00:25:30,202 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 00:25:33,136 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:31:47,401 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:32:12,833 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:32:12,834 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:32:13,263 
INFO 
Call started...sid: CAf86156549fadca36e57ecad7229ae7f9 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:33:20,055 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:46:10,590 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:46:13,216 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:46:13,216 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:46:13,600 
INFO 
Call started...sid: CAfe9c22e7dd0bc09dbfdffeb5b93b1cd5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:46:30,216 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 00:46:39,560 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:46:44,185 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:46:44,525 
INFO 
Call started...sid: CA3dd14b2a6da66dcd79bf7c9ef7af20c8 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:49:44,725 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-28 00:49:46,522 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:49:46,523 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:49:46,905 
INFO 
Call started...sid: CAefcae20960e3dda1c96bf2d2082eaa10 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:50:02,582 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:52:55,712 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:52:59,102 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:52:59,104 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:52:59,721 
INFO 
Call started...sid: CAcd004489127f197ee20ce44413413f39 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:53:10,398 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CAcd004489127f197ee20ce44413413f39&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:18,836 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:18,943 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:25,088 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:25,213 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:33,721 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:33,821 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:40,035 
INFO 

COMPLETE URL: http://59ef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:53:41,116 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 00:57:08,208 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 00:57:11,123 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:57:11,124 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:57:11,539 
INFO 
Call started...sid: CAbae00bb0aa8a2f6015878b11a54ebcd0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:57:12,346 
INFO 
Forced shutdown requested. Exiting the program now... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 31, in <module>

2024-04-28 00:57:16,045 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 00:57:16,045 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 00:57:16,718 
INFO 
Call started...sid: CA04c14afe36d6e055744bc8005f9301ef 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 00:57:25,399 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CA04c14afe36d6e055744bc8005f9301ef&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:27,873 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:28,093 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:30,846 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:30,957 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:33,422 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:33,530 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:35,436 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:35,554 
INFO 

COMPLETE URL: http://c8f4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 00:57:36,022 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 00:57:42,740 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:06:39,987 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 01:06:41,856 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 01:06:41,856 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 01:06:42,407 
INFO 
Call started...sid: CA27b515b0269f32dcb147aae479a45c7c 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 01:06:49,614 
INFO 

COMPLETE URL: http://f240-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CA27b515b0269f32dcb147aae479a45c7c&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:06:58,404 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:07:05,267 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 01:07:06,988 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 01:07:06,989 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 01:07:07,307 
INFO 
Call started...sid: CAfccfbcdb5d8ed23913eded2ff38e7f9f 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 01:07:13,976 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CAfccfbcdb5d8ed23913eded2ff38e7f9f&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:16,359 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:16,365 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:07:20,729 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:20,734 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:07:27,081 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:27,085 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:07:32,200 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:32,206 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:07:37,472 
INFO 

COMPLETE URL: http://3ed4-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:07:37,666 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 01:07:48,416 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:10:56,623 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 01:11:00,367 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 01:11:00,367 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 01:11:01,216 
INFO 
Call started...sid: CA6f99975448f0957ff25bf09821d4c65f 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 01:11:08,271 
INFO 

COMPLETE URL: http://1eef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CA6f99975448f0957ff25bf09821d4c65f&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:11:12,773 
INFO 

COMPLETE URL: http://1eef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:11:12,778 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:11:17,019 
INFO 

COMPLETE URL: http://1eef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:11:17,023 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=2 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:11:23,628 
INFO 

COMPLETE URL: http://1eef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:11:23,633 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:11:32,456 
INFO 

COMPLETE URL: http://1eef-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:11:32,461 
INFO 
response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=4 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:11:37,422 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:20:30,581 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 01:21:04,704 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 01:21:04,705 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 01:21:05,115 
INFO 
Call started...sid: CA3a559c8028873c040028bb8882c4e58f 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 01:21:19,147 
INFO 

COMPLETE URL: http://d29a-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CA3a559c8028873c040028bb8882c4e58f&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:21:24,344 
INFO 

COMPLETE URL: http://d29a-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=0
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:21:24,348 
INFO 

response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:21:34,828 
INFO 

COMPLETE URL: http://d29a-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 21, in intro_message

2024-04-28 01:21:34,833 
INFO 

response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:21:47,314 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:27:51,007 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 01:27:56,092 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 01:27:56,092 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 01:27:56,722 
INFO 
Call started...sid: CA37e281cb9e2f152c88bd1e5bce116d54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 01:28:10,007 
INFO 

COMPLETE URL: http://eece-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?Called=%2B13149402059&ToState=MO&CallerCountry=US&Direction=outbound-api&CallerState=&ToZip=&CallSid=CA37e281cb9e2f152c88bd1e5bce116d54&To=%2B13149402059&CallerZip=&ToCountry=US&CalledZip=&ApiVersion=2010-04-01&CalledCity=&CallStatus=in-progress&From=%2B18333156419&AccountSid=AC6eb74d248ace0c243a8ef6772acd0eea&CalledCountry=US&CallerCity=&ToCity=&FromCountry=US&Caller=%2B18333156419&FromCity=&CalledState=MO&FromZip=&FromState=
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 19, in intro_message

2024-04-28 01:28:12,714 
INFO 

COMPLETE URL: http://eece-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 19, in intro_message

2024-04-28 01:28:12,720 
INFO 

response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:28:17,251 
INFO 

COMPLETE URL: http://eece-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 19, in intro_message

2024-04-28 01:28:17,256 
INFO 

response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:28:19,781 
INFO 

COMPLETE URL: http://eece-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 19, in intro_message

2024-04-28 01:28:19,785 
INFO 

response not understood on path: call/intro_message/54?iteration_count=0&timeout_count=4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 24, in handle_unrecognizable_response

2024-04-28 01:28:22,514 
INFO 

COMPLETE URL: http://eece-2600-6c40-59f0-ed20-d447-9f2-eb4f-3af7.ngrok-free.app/call/intro_message/54?iteration_count=0&timeout_count=4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 19, in intro_message

2024-04-28 01:28:23,214 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 01:28:28,193 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 01:55:38,883 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:27:42,659 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:27:42,659 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:27:43,199 
INFO 
Call started...sid: CA51e17af25ed7bd2878ef0d9525b73236 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 02:28:19,672 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 02:28:56,092 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:28:58,117 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:28:58,117 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:28:58,444 
INFO 
Call started...sid: CA347cdf66bfcdc04190ba4e786a3cae12 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 02:29:34,899 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 02:31:34,791 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:31:36,808 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:31:36,809 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:31:37,273 
INFO 
Call started...sid: CA22710bf4ba151be0e1d729335c6e236a 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 02:33:16,895 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 02:33:26,122 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 02:49:21,156 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:49:26,176 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:49:26,176 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:49:26,617 
INFO 
Call started...sid: CA8b1a543cdd22084bf136bedfc809cf21 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 02:49:57,543 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 02:50:34,593 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:50:49,551 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:50:49,551 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:50:50,335 
INFO 
Call started...sid: CA1f0d69ffb9228131795d54f75194eaa0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 02:51:06,236 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 02:52:24,774 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 02:59:50,287 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 02:59:50,288 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 02:59:51,085 
INFO 
Call started...sid: CA539e95f1470367eef29e48238ecd2c6e 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:00:07,142 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:05:51,007 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:05:55,020 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:05:55,020 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:05:56,070 
INFO 
Call started...sid: CAdac4b4ee34deb6e0ec5abc0283830130 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:06:53,525 
INFO 
Response: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 56, 'available_female_docs': 12, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 99, in handle_failed_call

2024-04-28 03:07:03,679 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:07:58,512 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:08:01,210 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:08:01,211 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:08:02,044 
INFO 
Call started...sid: CAd89a35587f85914291bb58f7d753e583 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:08:33,515 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:08:56,013 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:08:59,868 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:08:59,869 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:09:00,263 
INFO 
Call started...sid: CA47c0673c7232b998e1c9fb2df4bf6cf7 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:09:10,729 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:09:14,590 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:09:17,194 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:09:17,194 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:09:17,529 
INFO 
Call started...sid: CA3da80365ea56352ffb002f1da6b68e43 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:09:53,594 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:11:37,806 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:11:40,297 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:11:40,298 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:11:40,738 
INFO 
Call started...sid: CA67fb39d60cc0a147cbb32cf1bfb23605 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:12:01,416 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA67fb39d60cc0a147cbb32cf1bfb23605', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:12:06,499 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:14:20,762 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:14:23,218 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:14:23,220 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:14:23,646 
INFO 
Call started...sid: CAce1b804a56741359ef829053b7796cdc 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:14:56,447 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CAce1b804a56741359ef829053b7796cdc', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:15:00,624 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:15:57,368 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:16:00,449 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:16:00,450 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:16:00,809 
INFO 
Call started...sid: CA174abea9b29a679e9db87d7ce154852b 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:16:26,622 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA174abea9b29a679e9db87d7ce154852b', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:16:31,712 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:16:44,067 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:16:46,530 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:16:46,531 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:16:46,864 
INFO 
Call started...sid: CAc737ec897a071286ff942ae180e7686f 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:17:07,110 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CAc737ec897a071286ff942ae180e7686f', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:17:12,810 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:18:34,587 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:18:39,165 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:18:39,166 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:18:39,560 
INFO 
Call started...sid: CAbe2d5426bb563abbd1cee224d5a5935d 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:18:55,425 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CAbe2d5426bb563abbd1cee224d5a5935d', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:19:00,251 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:19:17,046 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:19:18,839 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:19:18,840 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:19:19,201 
INFO 
Call started...sid: CA24c86a44f8ce3543fba1be554e843829 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:19:33,961 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA24c86a44f8ce3543fba1be554e843829', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:19:40,020 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:21:06,484 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:21:10,174 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:21:10,175 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:21:10,544 
INFO 
Call started...sid: CA810b159060a0e55d33df35a17074673a 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:21:24,056 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA810b159060a0e55d33df35a17074673a', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:21:37,301 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 82, in handle_successful_call

2024-04-28 03:21:37,303 
INFO 
call was a success, male docs: 3, female docs: 5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 87, in handle_successful_call

2024-04-28 03:21:37,634 
INFO 
new clinic data in db: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 3, 'available_female_docs': 5, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 91, in handle_successful_call

2024-04-28 03:21:46,572 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:35:30,987 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:43:31,116 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:43:31,117 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:43:31,761 
INFO 
Call started...sid: CAb5b947914a220990fe1647f3bb6881dd 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:43:54,732 
INFO 

response not understood on path: call/handle_intro_message_response/54?prompt_retry_count=0&timeouts_count=0&invalid_input_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 03:44:16,976 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '4', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CAb5b947914a220990fe1647f3bb6881dd', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:44:34,312 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:45:31,195 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:45:33,314 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:45:33,315 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:45:33,679 
INFO 
Call started...sid: CA00b4e0377b3e9323c73da6210af463f1 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:45:57,843 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA00b4e0377b3e9323c73da6210af463f1', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:46:45,747 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:50:38,824 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:50:42,327 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:50:42,328 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:50:42,725 
INFO 
Call started...sid: CA97d5a0a51e13b76284ad32dceb6cadff 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:50:54,164 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA97d5a0a51e13b76284ad32dceb6cadff', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:51:33,955 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 03:53:37,616 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 03:54:13,955 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 03:54:13,956 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 03:54:14,350 
INFO 
Call started...sid: CA12f924349e41aa00e5bb03177b1726c8 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 03:54:31,457 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA12f924349e41aa00e5bb03177b1726c8', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 03:54:55,552 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:02:31,866 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:02:34,813 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:02:34,814 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:02:35,264 
INFO 
Call started...sid: CA477488625941729af36c310e5d027880 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:02:53,263 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA477488625941729af36c310e5d027880', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:03:16,409 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:04:29,100 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:04:33,609 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:04:33,609 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:04:34,411 
INFO 
Call started...sid: CA42d5438aa4453daa9f2eaf4db8b05618 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:04:49,555 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA42d5438aa4453daa9f2eaf4db8b05618', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:05:07,085 
INFO 
Only male docs can be updated 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/db/database_manager.py", line 29, in update_db_on_failed_call

2024-04-28 04:05:15,907 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:07:22,937 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:07:25,409 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:07:25,409 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:07:26,088 
INFO 
Call started...sid: CA2a004b648cd34561b78547bc4257a26a 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:07:41,787 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '3', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA2a004b648cd34561b78547bc4257a26a', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:07:59,369 
INFO 
Only male docs can be updated 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/db/database_manager.py", line 27, in update_db_on_failed_call

2024-04-28 04:07:59,686 
INFO 
partial db update: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 3, 'available_female_docs': 5, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 107, in handle_failed_call

2024-04-28 04:08:12,865 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:08:48,027 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:08:48,861 
INFO 
Call started...sid: CA72436fe729fca58f5ff827a85c0b3dcc 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:09:18,350 
INFO 

response not understood on path: call/handle_intro_message_response/55?prompt_retry_count=0&timeouts_count=0&invalid_input_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:09:33,201 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '*', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA72436fe729fca58f5ff827a85c0b3dcc', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:09:40,182 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:10:12,006 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:10:15,533 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:10:15,533 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:10:15,929 
INFO 
Call started...sid: CAcaa95286eb58796d4cbff3adb4cf2ab5 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:10:30,557 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '*', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CAcaa95286eb58796d4cbff3adb4cf2ab5', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:10:30,560 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 149, in handle_number_male_doctors_response

2024-04-28 04:10:36,811 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:11:35,820 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:11:39,435 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:11:39,436 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:11:40,041 
INFO 
Call started...sid: CA58b9052e2be7d915bdf0d6511fe9ab25 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:11:57,920 
INFO 
FORM: {'msg': 'Gather End', 'Called': '+13149402059', 'Digits': '*', 'ToState': 'MO', 'CallerCountry': 'US', 'Direction': 'outbound-api', 'CallerState': '', 'ToZip': '', 'CallSid': 'CA58b9052e2be7d915bdf0d6511fe9ab25', 'To': '+13149402059', 'CallerZip': '', 'ToCountry': 'US', 'FinishedOnKey': '', 'CalledZip': '', 'ApiVersion': '2010-04-01', 'CalledCity': '', 'CallStatus': 'in-progress', 'From': '+18333156419', 'AccountSid': 'AC6eb74d248ace0c243a8ef6772acd0eea', 'CalledCountry': 'US', 'CallerCity': '', 'ToCity': '', 'FromCountry': 'US', 'Caller': '+18333156419', 'FromCity': '', 'CalledState': 'MO', 'FromZip': '', 'FromState': ''} 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 133, in handle_number_male_doctors_response

2024-04-28 04:11:57,922 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 149, in handle_number_male_doctors_response

2024-04-28 04:12:05,957 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:14:32,395 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:14:32,396 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:14:32,800 
INFO 
Call started...sid: CA64fd1e440b28b5b21844c9705e2a2b28 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:14:49,486 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 147, in handle_number_male_doctors_response

2024-04-28 04:14:53,735 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:20:48,375 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:20:53,896 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:20:53,897 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:20:54,450 
INFO 
Call started...sid: CA1e34878d74f53ddf0c11a4ccf6adb1e9 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:21:12,991 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 146, in handle_number_male_doctors_response

2024-04-28 04:21:12,995 
INFO 

response not understood on path: /call/ask_male_doctors_number/54?invalid_input_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:21:25,794 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:23:29,533 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:23:31,853 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:23:31,854 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:23:32,353 
INFO 
Call started...sid: CA6273f7a61ef8a6e56abe72f1d4044079 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:23:48,675 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 146, in handle_number_male_doctors_response

2024-04-28 04:23:48,680 
INFO 

response not understood on path: /call/handle_number_male_doctors_response/54?invalid_input_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:23:56,383 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 146, in handle_number_male_doctors_response

2024-04-28 04:23:56,387 
INFO 

response not understood on path: /call/handle_number_male_doctors_response/54?invalid_input_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:24:03,113 
INFO 
partial db update: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 3, 'available_female_docs': 5, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 107, in handle_failed_call

2024-04-28 04:24:14,074 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:24:42,795 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:24:43,112 
INFO 
Call started...sid: CA58dc4805576a09faddaa193050f352bf 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:25:26,592 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 211, in handle_number_female_doctors_response

2024-04-28 04:25:26,596 
INFO 

response not understood on path: /call/handle_female_doctors_number/55?invalid_input_count=1
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:25:33,591 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 211, in handle_number_female_doctors_response

2024-04-28 04:25:33,595 
INFO 

response not understood on path: /call/handle_female_doctors_number/55?invalid_input_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:25:41,487 
INFO 
Only male docs can be updated 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/db/database_manager.py", line 27, in update_db_on_failed_call

2024-04-28 04:25:41,723 
INFO 
partial db update: ('data', [{'name': "yohance's clinic 2", 'address': '2323 dele st', 'phone_number': '(314) 940-2059', 'rating': 4.2, 'available_male_docs': 1, 'available_female_docs': 0, 'last_call_date': '2024-04-28', 'id': 55, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 107, in handle_failed_call

2024-04-28 04:25:50,016 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:26:34,963 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:26:40,084 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:26:40,085 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:26:40,470 
INFO 
Call started...sid: CA1416b136a384e39943a74aa63d9a9f92 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:27:11,890 
INFO 
intro mess it is now: 0 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 83, in handle_successful_call

2024-04-28 04:27:11,894 
INFO 
call was a success, male docs: 1, female docs: 8 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 88, in handle_successful_call

2024-04-28 04:27:12,163 
INFO 
clinic id: 54. new clinic data in db: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 1, 'available_female_docs': 8, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': True}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 92, in handle_successful_call

2024-04-28 04:27:22,152 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:27:24,007 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 55 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:27:24,329 
INFO 
Call started...sid: CAa797fa57f6f4fda7aa6f6ea15722320e 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:27:49,896 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:27:59,925 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

2024-04-28 04:30:27,162 
INFO 
Received phone number: (314) 940-2059. Received clinic id: 54 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_single_clinic.py", line 18, in make_call

2024-04-28 04:30:27,162 
INFO 
Starting flask server... 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/app.py", line 13, in start_server

2024-04-28 04:30:27,755 
INFO 
Call started...sid: CAf86ca2bed91fc33c1f36859ff09f3fb3 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 74, in call_all_clinics

2024-04-28 04:31:12,021 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 211, in handle_number_female_doctors_response

2024-04-28 04:31:12,025 
INFO 

response not understood on path: /call/handle_female_doctors_number/54?invalid_input_count=2
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:31:18,021 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 211, in handle_number_female_doctors_response

2024-04-28 04:31:18,024 
INFO 

response not understood on path: /call/handle_female_doctors_number/54?invalid_input_count=3
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:31:23,729 
INFO 
type error exception thrown. error message: invalid literal for int() with base 10: '*' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/controller/call_flow_manager.py", line 211, in handle_number_female_doctors_response

2024-04-28 04:31:23,733 
INFO 

response not understood on path: /call/handle_female_doctors_number/54?invalid_input_count=4
 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 25, in handle_unrecognizable_response

2024-04-28 04:31:29,630 
INFO 
Only male docs can be updated 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/db/database_manager.py", line 27, in update_db_on_failed_call

2024-04-28 04:31:30,096 
INFO 
partial db update: ('data', [{'name': "yohance's clinic", 'address': '4545 Tampa Ave', 'phone_number': '(314) 940-2059', 'rating': 4.4, 'available_male_docs': 6, 'available_female_docs': 8, 'last_call_date': '2024-04-28', 'id': 54, 'last_call_success': False}]) 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/active_call_methods.py", line 107, in handle_failed_call

2024-04-28 04:31:40,177 
INFO 
final call status is: 'completed' 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 38, in check_call_status

2024-04-28 04:33:46,325 
INFO 
You chose to stop the program. Exiting program now. 
 	from File "/Users/yohance/Documents/find-me-a-doc/src/services/calls/call_all_clinics.py", line 102, in call_all_clinics

